// Delhi Metro Stations — sourced from delhimetrorail.info + coordinates
const STATIONS = [
  {name:"Adarsh Nagar",line:"Yellow Line",slug:"adarsh-nagar"},
  {name:"AIIMS",line:"Yellow Line",slug:"aiims"},
  {name:"Akshardham",line:"Blue Line",slug:"akshardham"},
  {name:"Alpha 1  Greater Noida",line:"Aqua Line",slug:"alpha-1-greater-noida"},
  {name:"Anand Vihar",line:"Pink Line",slug:"anand-vihar"},
  {name:"Arjan Garh",line:"Yellow Line",slug:"arjan-garh"},
  {name:"Arthala",line:"Pink Line",slug:"arthala"},
  {name:"Ashok Park Main",line:"Green Line",slug:"ashok-park-main"},
  {name:"Ashram",line:"Pink Line",slug:"ashram"},
  {name:"Azadpur",line:"Pink Line",slug:"azadpur"},
  {name:"Badarpur Border",line:"Violet Line",slug:"badarpur-border"},
  {name:"Badkal Mor",line:"Violet Line",slug:"badkal-mor"},
  {name:"Bahdurgarh City",line:"Green Line",slug:"bahdurgarh-city"},
  {name:"Barakhamba",line:"Blue Line",slug:"barakhamba"},
  {name:"Bata Chowk",line:"Violet Line",slug:"bata-chowk"},
  {name:"Belvedere Towers (Rapid Metro)",line:"Rapid Metro",slug:"belvedere-towers-rapid-metro"},
  {name:"Bhikaji Cama Place",line:"Magenta Line",slug:"bhikaji-cama-place"},
  {name:"Botanical Garden",line:"Magenta Line",slug:"botanical-garden"},
  {name:"Brigadier Hoshiar Singh",line:"Green Line",slug:"brigadier-hoshiar-singh"},
  {name:"Central Secretariat",line:"Yellow Line",slug:"central-secretariat"},
  {name:"Chandni Chowk",line:"Yellow Line",slug:"chandni-chowk"},
  {name:"Chawri Bazar",line:"Yellow Line",slug:"chawri-bazar"},
  {name:"Chhattarpur",line:"Yellow Line",slug:"chhattarpur"},
  {name:"Chirag Delhi",line:"Magenta Line",slug:"chirag-delhi"},
  {name:"Civil Lines",line:"Yellow Line",slug:"civil-lines"},
  {name:"Cyber City (Rapid Metro)",line:"Rapid Metro",slug:"cyber-city-rapid-metro"},
  {name:"Dabri Mor - Janakpuri South",line:"Magenta Line",slug:"dabri-mor-janakpuri-south"},
  {name:"Dashrath Puri",line:"Magenta Line",slug:"dashrath-puri"},
  {name:"Delhi Aerocity",line:"Airport Express",slug:"delhi-aerocity"},
  {name:"Delhi Cantt",line:"Pink Line",slug:"delhi-cantt"},
  {name:"Delhi Gate",line:"Violet Line",slug:"delhi-gate"},
  {name:"Delta 1 Greater Noida",line:"Aqua Line",slug:"delta-1-greater-noida"},
  {name:"Depot Greater Noida",line:"Aqua Line",slug:"depot-greater-noida"},
  {name:"Dhaula Kuan",line:"Airport Express",slug:"dhaula-kuan"},
  {name:"Dilli Haat INA",line:"Yellow Line",slug:"dilli-haat-ina"},
  {name:"Dilshad Garden",line:"Red Line",slug:"dilshad-garden"},
  {name:"DLF Phase 1 (Rapid Metro)",line:"Rapid Metro",slug:"dlf-phase-1-rapid-metro"},
  {name:"DLF Phase 2 (Rapid Metro)",line:"Rapid Metro",slug:"dlf-phase-2-rapid-metro"},
  {name:"DLF Phase 3 (Rapid Metro)",line:"Rapid Metro",slug:"dlf-phase-3-rapid-metro"},
  {name:"Durgabai Deshmukh South Campus",line:"Magenta Line",slug:"durgabai-deshmukh-south-campus"},
  {name:"Dwarka",line:"Grey Line",slug:"dwarka"},
  {name:"Dwarka Mor",line:"Blue Line",slug:"dwarka-mor"},
  {name:"Dwarka Sector 10",line:"Blue Line",slug:"dwarka-sector-10"},
  {name:"Dwarka Sector 11",line:"Blue Line",slug:"dwarka-sector-11"},
  {name:"Dwarka Sector 12",line:"Blue Line",slug:"dwarka-sector-12"},
  {name:"Dwarka Sector 13",line:"Blue Line",slug:"dwarka-sector-13"},
  {name:"Dwarka Sector 14",line:"Blue Line",slug:"dwarka-sector-14"},
  {name:"Dwarka Sector 21",line:"Blue Line",slug:"dwarka-sector-21"},
  {name:"Dwarka Sector 8",line:"Blue Line",slug:"dwarka-sector-8"},
  {name:"Dwarka Sector 9",line:"Blue Line",slug:"dwarka-sector-9"},
  {name:"East Azad Nagar",line:"Blue Line",slug:"east-azad-nagar"},
  {name:"Escorts Mujesar",line:"Violet Line",slug:"escorts-mujesar"},
  {name:"ESI BASAI DARAPUR",line:"Green Line",slug:"esi-basai-darapur"},
  {name:"Ghevra Metro station",line:"Green Line",slug:"ghevra-metro-station"},
  {name:"Ghitorni",line:"Yellow Line",slug:"ghitorni"},
  {name:"GNIDA Office",line:"Aqua Line",slug:"gnida-office"},
  {name:"Gokulpuri",line:"Red Line",slug:"gokulpuri"},
  {name:"Golf Course",line:"Blue Line",slug:"golf-course"},
  {name:"Govind Puri",line:"Violet Line",slug:"govind-puri"},
  {name:"Greater Kailash",line:"Violet Line",slug:"greater-kailash"},
  {name:"Green Park",line:"Yellow Line",slug:"green-park"},
  {name:"Guru Dronacharya",line:"Yellow Line",slug:"guru-dronacharya"},
  {name:"Guru Tegh Bahadur Nagar",line:"Yellow Line",slug:"guru-tegh-bahadur-nagar"},
  {name:"Haiderpur Badli Mor",line:"Red Line",slug:"haiderpur-badli-mor"},
  {name:"Hauz Khas",line:"Magenta Line",slug:"hauz-khas"},
  {name:"Hindon River",line:"Pink Line",slug:"hindon-river"},
  {name:"Huda City Centre",line:"Yellow Line",slug:"huda-city-centre"},
  {name:"IFFCO Chowk",line:"Yellow Line",slug:"iffco-chowk"},
  {name:"IGI Airport",line:"Airport Express",slug:"igi-airport"},
  {name:"IIT Delhi",line:"Yellow Line",slug:"iit-delhi"},
  {name:"Inderlok",line:"Green Line",slug:"inderlok"},
  {name:"Indraprastha",line:"Blue Line",slug:"indraprastha"},
  {name:"IP Extension",line:"Pink Line",slug:"ip-extension"},
  {name:"ITO",line:"Violet Line",slug:"ito"},
  {name:"Jaffrabad",line:"Red Line",slug:"jaffrabad"},
  {name:"Jahangirpuri",line:"Yellow Line",slug:"jahangirpuri"},
  {name:"Jama Masjid",line:"Violet Line",slug:"jama-masjid"},
  {name:"JAMIA MILLIA ISLAMIA",line:"Magenta Line",slug:"jamia-millia-islamia"},
  {name:"Janak Puri East",line:"Blue Line",slug:"janak-puri-east"},
  {name:"Janak Puri West",line:"Blue Line",slug:"janak-puri-west"},
  {name:"Jangpura",line:"Violet Line",slug:"jangpura"},
  {name:"Janpath",line:"Violet Line",slug:"janpath"},
  {name:"Jasola",line:"Violet Line",slug:"jasola"},
  {name:"Jasola Vihar Shaheen Bagh",line:"Magenta Line",slug:"jasola-vihar-shaheen-bagh"},
  {name:"Jawaharlal Nehru Stadium",line:"Violet Line",slug:"jawaharlal-nehru-stadium"},
  {name:"Jhandewalan",line:"Blue Line",slug:"jhandewalan"},
  {name:"Jhil Mil",line:"Red Line",slug:"jhil-mil"},
  {name:"Johri Enclave",line:"Pink Line",slug:"johri-enclave"},
  {name:"Jorbagh",line:"Yellow Line",slug:"jorbagh"},
  {name:"Kailash Colony",line:"Violet Line",slug:"kailash-colony"},
  {name:"Kalindi Kunj",line:"Magenta Line",slug:"kalindi-kunj"},
  {name:"Kalkaji Mandir",line:"Magenta Line",slug:"kalkaji-mandir"},
  {name:"Kanhaiya Nagar",line:"Red Line",slug:"kanhaiya-nagar"},
  {name:"Karkar Duma",line:"Pink Line",slug:"karkar-duma"},
  {name:"Karkarduma Court",line:"Pink Line",slug:"karkarduma-court"},
  {name:"Karol Bagh",line:"Blue Line",slug:"karol-bagh"},
  {name:"Kashmere Gate",line:"Violet Line",slug:"kashmere-gate"},
  {name:"Kaushambi",line:"Blue Line",slug:"kaushambi"},
  {name:"Keshav Puram",line:"Red Line",slug:"keshav-puram"},
  {name:"Khan Market",line:"Violet Line",slug:"khan-market"},
  {name:"Kirti Nagar",line:"Green Line",slug:"kirti-nagar"},
  {name:"Knowledge Park II",line:"Aqua Line",slug:"knowledge-park-ii"},
  {name:"Kohat Enclave",line:"Red Line",slug:"kohat-enclave"},
  {name:"Krishna Nagar",line:"Blue Line",slug:"krishna-nagar"},
  {name:"Lajpat Nagar",line:"Violet Line",slug:"lajpat-nagar"},
  {name:"Lal Quila",line:"Violet Line",slug:"lal-quila"},
  {name:"Laxmi Nagar",line:"Blue Line",slug:"laxmi-nagar"},
  {name:"Lok Kalyan Marg",line:"Yellow Line",slug:"lok-kalyan-marg"},
  {name:"Madipur",line:"Green Line",slug:"madipur"},
  {name:"Maharaja Surajmal Stadium",line:"Green Line",slug:"maharaja-surajmal-stadium"},
  {name:"Majlis Park",line:"Pink Line",slug:"majlis-park"},
  {name:"Major Mohit Sharma",line:"Pink Line",slug:"major-mohit-sharma"},
  {name:"Malviya Nagar",line:"Yellow Line",slug:"malviya-nagar"},
  {name:"Mandawali - West Vinod Nagar",line:"Pink Line",slug:"mandawali-west-vinod-nagar"},
  {name:"Mandi House",line:"Violet Line",slug:"mandi-house"},
  {name:"Mansarovar Park",line:"Red Line",slug:"mansarovar-park"},
  {name:"Maujpur",line:"Red Line",slug:"maujpur"},
  {name:"Maya Puri",line:"Pink Line",slug:"maya-puri"},
  {name:"Mayur Vihar Extention",line:"Blue Line",slug:"mayur-vihar-extention"},
  {name:"Mayur Vihar Phase-1",line:"Blue Line",slug:"mayur-vihar-phase-1"},
  {name:"Mayur Vihar Pocket I",line:"Pink Line",slug:"mayur-vihar-pocket-i"},
  {name:"Mewala Maharajpur",line:"Violet Line",slug:"mewala-maharajpur"},
  {name:"MG Road",line:"Yellow Line",slug:"mg-road"},
  {name:"Model Town",line:"Yellow Line",slug:"model-town"},
  {name:"Mohan Estate",line:"Violet Line",slug:"mohan-estate"},
  {name:"Mohan Nagar",line:"Pink Line",slug:"mohan-nagar"},
  {name:"Moolchand",line:"Violet Line",slug:"moolchand"},
  {name:"Moti Nagar",line:"Blue Line",slug:"moti-nagar"},
  {name:"Moulsari Avenue (Rapid Metro)",line:"Rapid Metro",slug:"moulsari-avenue-rapid-metro"},
  {name:"Mundka",line:"Green Line",slug:"mundka"},
  {name:"Mundka Industrial Area (MIA)",line:"Green Line",slug:"mundka-industrial-area-mia"},
  {name:"Munirka",line:"Magenta Line",slug:"munirka"},
  {name:"N.H.P.C. Chowk",line:"Violet Line",slug:"nhpc-chowk"},
  {name:"Najafgarh",line:"Grey Line",slug:"najafgarh"},
  {name:"Nangli",line:"Grey Line",slug:"nangli"},
  {name:"Nangloi",line:"Green Line",slug:"nangloi"},
  {name:"Nangloi Railway Station",line:"Green Line",slug:"nangloi-railway-station"},
  {name:"Naraina Vihar",line:"Pink Line",slug:"naraina-vihar"},
  {name:"Nawada",line:"Blue Line",slug:"nawada"},
  {name:"Neelam Chowk Ajronda",line:"Violet Line",slug:"neelam-chowk-ajronda"},
  {name:"Nehru Enclave",line:"Magenta Line",slug:"nehru-enclave"},
  {name:"Nehru Place",line:"Violet Line",slug:"nehru-place"},
  {name:"Netaji Subash Place",line:"Pink Line",slug:"netaji-subash-place"},
  {name:"New Ashok Nagar",line:"Blue Line",slug:"new-ashok-nagar"},
  {name:"New Delhi",line:"Yellow Line",slug:"new-delhi"},
  {name:"New Delhi-Airport Express",line:"Airport Express",slug:"new-delhi-airport-express"},
  {name:"Nirman Vihar",line:"Blue Line",slug:"nirman-vihar"},
  {name:"Noida City Center",line:"Blue Line",slug:"noida-city-center"},
  {name:"Noida Electronic City",line:"Blue Line",slug:"noida-electronic-city"},
  {name:"Noida Sector 101",line:"Aqua Line",slug:"noida-sector-101"},
  {name:"Noida Sector 137",line:"Aqua Line",slug:"noida-sector-137"},
  {name:"Noida Sector 142",line:"Aqua Line",slug:"noida-sector-142"},
  {name:"Noida Sector 143",line:"Aqua Line",slug:"noida-sector-143"},
  {name:"Noida Sector 144",line:"Aqua Line",slug:"noida-sector-144"},
  {name:"Noida Sector 145",line:"Aqua Line",slug:"noida-sector-145"},
  {name:"Noida Sector 146",line:"Aqua Line",slug:"noida-sector-146"},
  {name:"Noida Sector 147",line:"Aqua Line",slug:"noida-sector-147"},
  {name:"Noida Sector 148",line:"Aqua Line",slug:"noida-sector-148"},
  {name:"Noida Sector 15",line:"Blue Line",slug:"noida-sector-15"},
  {name:"Noida Sector 16",line:"Blue Line",slug:"noida-sector-16"},
  {name:"Noida Sector 18",line:"Blue Line",slug:"noida-sector-18"},
  {name:"Noida Sector 34",line:"Aqua Line",slug:"noida-sector-34"},
  {name:"Noida Sector 50",line:"Aqua Line",slug:"noida-sector-50"},
  {name:"Noida Sector 51",line:"Aqua Line",slug:"noida-sector-51"},
  {name:"Noida Sector 52",line:"Blue Line",slug:"noida-sector-52"},
  {name:"Noida Sector 59",line:"Aqua Line",slug:"noida-sector-59"},
  {name:"Noida Sector 61",line:"Aqua Line",slug:"noida-sector-61"},
  {name:"Noida Sector 62",line:"Blue Line",slug:"noida-sector-62"},
  {name:"Noida Sector 76",line:"Aqua Line",slug:"noida-sector-76"},
  {name:"Noida Sector 81",line:"Aqua Line",slug:"noida-sector-81"},
  {name:"Noida Sector 83",line:"Aqua Line",slug:"noida-sector-83"},
  {name:"NSEZ Noida",line:"Aqua Line",slug:"nsez-noida"},
  {name:"Okhla",line:"Violet Line",slug:"okhla"},
  {name:"Okhla Bird Sanctuary",line:"Magenta Line",slug:"okhla-bird-sanctuary"},
  {name:"Okhla NSIC",line:"Magenta Line",slug:"okhla-nsic"},
  {name:"Okhla Vihar",line:"Magenta Line",slug:"okhla-vihar"},
  {name:"Old Faridabad",line:"Violet Line",slug:"old-faridabad"},
  {name:"Palam",line:"Magenta Line",slug:"palam"},
  {name:"Panchsheel Park",line:"Magenta Line",slug:"panchsheel-park"},
  {name:"Pandit Shree Ram Sharma",line:"Green Line",slug:"pandit-shree-ram-sharma"},
  {name:"Pari Chowk  Greater Noida",line:"Aqua Line",slug:"pari-chowk-greater-noida"},
  {name:"Paschim Vihar (East)",line:"Green Line",slug:"paschim-vihar-east"},
  {name:"Paschim Vihar (West)",line:"Green Line",slug:"paschim-vihar-west"},
  {name:"Patel Chowk",line:"Yellow Line",slug:"patel-chowk"},
  {name:"Patel Nagar",line:"Blue Line",slug:"patel-nagar"},
  {name:"Peera Garhi",line:"Green Line",slug:"peera-garhi"},
  {name:"Pitam Pura",line:"Red Line",slug:"pitam-pura"},
  {name:"Pratap Nagar",line:"Pink Line",slug:"pratap-nagar"},
  {name:"Preet Vihar",line:"Blue Line",slug:"preet-vihar"},
  {name:"Pul Bangash",line:"Red Line",slug:"pul-bangash"},
  {name:"Punjabi Bagh",line:"Green Line",slug:"punjabi-bagh"},
  {name:"Punjabi Bagh West",line:"Pink Line",slug:"punjabi-bagh-west"},
  {name:"Qutab Minar",line:"Yellow Line",slug:"qutab-minar"},
  {name:"R K Ashram Marg",line:"Blue Line",slug:"r-k-ashram-marg"},
  {name:"Raj Bagh",line:"Red Line",slug:"raj-bagh"},
  {name:"Raja Nahar Singh",line:"Violet Line",slug:"raja-nahar-singh"},
  {name:"Rajdhani Park",line:"Green Line",slug:"rajdhani-park"},
  {name:"Rajendra Place",line:"Blue Line",slug:"rajendra-place"},
  {name:"Rajiv Chowk",line:"Blue Line",slug:"rajiv-chowk"},
  {name:"Rajouri Garden",line:"Pink Line",slug:"rajouri-garden"},
  {name:"Ramesh Nagar",line:"Blue Line",slug:"ramesh-nagar"},
  {name:"Rithala",line:"Red Line",slug:"rithala"},
  {name:"RK Puram",line:"Magenta Line",slug:"rk-puram"},
  {name:"Rohini East",line:"Red Line",slug:"rohini-east"},
  {name:"Rohini Sector 18-19",line:"Red Line",slug:"rohini-sector-18-19"},
  {name:"Rohini West",line:"Red Line",slug:"rohini-west"},
  {name:"Sadar Bazaar Cantonment",line:"Magenta Line",slug:"sadar-bazaar-cantonment"},
  {name:"Saket",line:"Yellow Line",slug:"saket"},
  {name:"Samaypur Badli",line:"Yellow Line",slug:"samaypur-badli"},
  {name:"Sant Surdas - Sihi",line:"Violet Line",slug:"sant-surdas-sihi"},
  {name:"Sarai",line:"Magenta Line",slug:"sarai"},
  {name:"Sarai Kale Khan Hazrat Nizamuddin",line:"Pink Line",slug:"sarai-kale-khan-hazrat-nizamuddin"},
  {name:"Sarita Vihar",line:"Violet Line",slug:"sarita-vihar"},
  {name:"Sarojini Nagar",line:"Pink Line",slug:"sarojini-nagar"},
  {name:"Satguru Ram Singh Marg",line:"Green Line",slug:"satguru-ram-singh-marg"},
  {name:"Sector 28 Faridabad",line:"Violet Line",slug:"sector-28-faridabad"},
  {name:"Sector 42-43 (Rapid Metro)",line:"Rapid Metro",slug:"sector-42-43-rapid-metro"},
  {name:"Sector 53-54 (Rapid Metro)",line:"Rapid Metro",slug:"sector-53-54-rapid-metro"},
  {name:"Sector 54 Chowk (Rapid Metro)",line:"Rapid Metro",slug:"sector-54-chowk-rapid-metro"},
  {name:"Sector 55-66 (Rapid Metro)",line:"Rapid Metro",slug:"sector-55-66-rapid-metro"},
  {name:"Seelampur",line:"Red Line",slug:"seelampur"},
  {name:"Shadipur",line:"Blue Line",slug:"shadipur"},
  {name:"Shahdara",line:"Red Line",slug:"shahdara"},
  {name:"Shaheed Nagar",line:"Red Line",slug:"shaheed-nagar"},
  {name:"Shaheed Sthal(New Bus Adda)",line:"Pink Line",slug:"shaheed-sthalnew-bus-adda"},
  {name:"Shakurpur",line:"Pink Line",slug:"shakurpur"},
  {name:"Shalimar Bagh",line:"Pink Line",slug:"shalimar-bagh"},
  {name:"Shankar Vihar",line:"Magenta Line",slug:"shankar-vihar"},
  {name:"Shastri Nagar",line:"Red Line",slug:"shastri-nagar"},
  {name:"Shastri Park",line:"Red Line",slug:"shastri-park"},
  {name:"Shiv Vihar",line:"Pink Line",slug:"shiv-vihar"},
  {name:"Shivaji Park",line:"Green Line",slug:"shivaji-park"},
  {name:"Shivaji Stadium",line:"Airport Express",slug:"shivaji-stadium"},
  {name:"Shyam park",line:"Pink Line",slug:"shyam-park"},
  {name:"Sikandarpur",line:"Yellow Line",slug:"sikandarpur"},
  {name:"Sikandarpur (Rapid Metro)",line:"Rapid Metro",slug:"sikandarpur-rapid-metro"},
  {name:"Sir Vishweshwaraiah Moti Bagh",line:"Magenta Line",slug:"sir-vishweshwaraiah-moti-bagh"},
  {name:"South Extension",line:"Pink Line",slug:"south-extension"},
  {name:"Subhash Nagar",line:"Blue Line",slug:"subhash-nagar"},
  {name:"Sukhdev Vihar",line:"Magenta Line",slug:"sukhdev-vihar"},
  {name:"Sultanpur",line:"Yellow Line",slug:"sultanpur"},
  {name:"Supreme Court (Pragati Maidan)",line:"Blue Line",slug:"supreme-court-pragati-maidan"},
  {name:"Tagore Garden",line:"Blue Line",slug:"tagore-garden"},
  {name:"Terminal 1 IGI Airport",line:"Magenta Line",slug:"terminal-1-igi-airport"},
  {name:"Tikri Border",line:"Green Line",slug:"tikri-border"},
  {name:"Tikri Kalan",line:"Green Line",slug:"tikri-kalan"},
  {name:"Tilak Nagar",line:"Blue Line",slug:"tilak-nagar"},
  {name:"Tis Hazari",line:"Red Line",slug:"tis-hazari"},
  {name:"Trilokpuri Sanjay Lake",line:"Pink Line",slug:"trilokpuri-sanjay-lake"},
  {name:"Tughlakabad",line:"Violet Line",slug:"tughlakabad"},
  {name:"Udyog Bhawan",line:"Yellow Line",slug:"udyog-bhawan"},
  {name:"Udyog Nagar",line:"Green Line",slug:"udyog-nagar"},
  {name:"Uttam Nagar East",line:"Blue Line",slug:"uttam-nagar-east"},
  {name:"Uttam Nagar West",line:"Blue Line",slug:"uttam-nagar-west"},
  {name:"Vaishali",line:"Blue Line",slug:"vaishali"},
  {name:"Vasant Vihar",line:"Magenta Line",slug:"vasant-vihar"},
  {name:"Vidhan Sabha",line:"Yellow Line",slug:"vidhan-sabha"},
  {name:"Vinobapuri",line:"Pink Line",slug:"vinobapuri"},
  {name:"Vinod Nagar East",line:"Pink Line",slug:"vinod-nagar-east"},
  {name:"Vishwavidyalaya",line:"Yellow Line",slug:"vishwavidyalaya"},
  {name:"Welcome",line:"Red Line",slug:"welcome"},
  {name:"Yamuna Bank",line:"Blue Line",slug:"yamuna-bank"},
];
